<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Sardanapal.Identity.Authorization Tests</Title>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Sardanapal.Identity.Authorization\Sardanapal.Identity.Authorization.csproj" />
    </ItemGroup>

</Project>
