<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Sardanapal.Identity.Authorization.Data Tests</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="NSubstitute" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Sardanapal.Identity.Authorization.Data\Sardanapal.Identity.Authorization.Data.csproj" />
    </ItemGroup>

</Project>
